# Managed by PteroProtect
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess Off

SecRequestBodyLimit 26214400
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecArgumentsLimit 1000
SecPcreMatchLimit 100000
SecPcreMatchLimitRecursion 100000

SecAuditEngine RelevantOnly
SecAuditLogType Serial
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts ABIJDEFHZ
SecAuditLogFormat JSON

SecTmpDir /tmp
SecDataDir /tmp

# Core Rule Set and local exclusions.
Include /etc/nginx/modsec/crs-setup.conf
Include /etc/nginx/modsec/rules/*.conf
Include /etc/nginx/modsec/local-exclusions.conf
