upstream php_codespace_dummy {
    server unix:/run/php/php8.3-fpm.sock;
}

server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name 10.0.0.194 _;

    root /workspaces/Danex/.codespaces/mock/var/www/pterodactyl/public;
    index index.php index.html;
    charset utf-8;

    include /workspaces/Danex/.codespaces/mock/etc/nginx/snippets/pteroprotect_server.conf;

    location / {
        limit_conn pteroprotect_global_conn 400;
        limit_req zone=pteroprotect_global_req burst=120 nodelay;
        limit_conn pteroprotect_conn 60;
        limit_req zone=pteroprotect_req burst=60 nodelay;
        auth_request /__pteroprotect/challenge/check;
        error_page 401 = @pteroprotect_challenge_redirect;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        try_files $uri =404;
        fastcgi_pass php_codespace_dummy;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    access_log /workspaces/Danex/.codespaces/mock/var/log/nginx/pteroprotect.access.log;
    error_log /workspaces/Danex/.codespaces/mock/var/log/nginx/pterodactyl.app-error.log warn;
}
